### ISSUE TITLE
WebStorm 2016.3 .styleLintrc... works?

### ISSUE THREAD

**Issue by davidctj** [styled-components/stylelint-processor-styled-components#10]
WebStorm recently released a version which support styleLint, and then I do the same step as mentioned on the homepage styleLint, but it is not working, here's the error:
```
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at C:\WebstormProjects\webroot\node_modules\stylelint\dist\augmentConfig.js:300:23
    at Array.forEach (native)
    at addProcessorFunctions (C:\WebstormProjects\webroot\node_modules\stylelint\dist\augmentConfig.js:290:58)
```

So, is someone working on intellij/webstorm plugin for that?

**Comment by meded90** [comment]
https://github.com/styled-components/styled-components/issues/176

**Comment by ismay** [comment]
I'm not familiar with webstorm, but is there any reason that results for webstorm would vary from other usecases of this plugin (cli use of stylelint for example)? Because there shouldn't be any difference.

I suspect this is an issue related to webstorm, and not necessarily this plugin, but please correct me if I'm wrong.

**Comment by ismay** [comment]
I'll close this due to inactivity and it seeming to be related to webstorm and not this library directly. But feel free to comment or let me know if it is directly related to this lib.
