### ISSUE TITLE
SyntaxError: Unexpected token when using wildcard in the file path

### ISSUE THREAD

**Issue by liunaijia** [styled-components/stylelint-processor-styled-components#104]
Hello,

When I run
```
npx stylelint './src/**/*.jsx'
```

It caused the error as follows:
```
SyntaxError: Unexpected token, expected ; (8:11)
    at Parser.pp$5.raise (/Users/me/myProject/node_modules/stylelint-processor-styled-components/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/me/myProject/node_modules/stylelint-processor-styled-components/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp.semicolon (/Users/me/myProject/node_modules/stylelint-processor-styled-components/node_modules/babylon/lib/index.js:1742:38)
    at Parser.pp$1.parseVarStatement (/Users/me/myProject/node_modules/stylelint-processor-styled-components/node_modules/babylon/lib/index.js:2170:8)
    at Parser.pp$1.parseStatement (/Users/me/myProject/node_modules/stylelint-processor-styled-components/node_modules/babylon/lib/index.js:1861:19)
    at Parser.parseStatement (/Users/me/myProject/node_modules/stylelint-processor-styled-components/node_modules/babylon/lib/index.js:5910:22)
    at Parser.pp$1.parseBlockBody (/Users/me/myProject/node_modules/stylelint-processor-styled-components/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/Users/me/myProject/node_modules/stylelint-processor-styled-components/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/Users/me/myProject/node_modules/stylelint-processor-styled-components/node_modules/babylon/lib/index.js:1673:17)
    at Object.parse (/Users/me/myProject/node_modules/stylelint-processor-styled-components/node_modules/babylon/lib/index.js:7305:37)
```

However, if I run stylelint against a single file it works.

```
npx stylelint './src/**/MyComponent.jsx'
```

Environment:
- stylelint: 8.0.0
- styled-components: 2.1.2
- stylelint-config-standard: 17.0.0
- stylelint-processor-styled-components: 0.3.0

Config:
```
// .stylelintrc.js
module.exports = {
  extends: 'stylelint-config-standard',
  syntax: 'scss',
  processors: ["stylelint-processor-styled-components"],
};

```

**Comment by emilgoldsmith** [comment]
Hi @liunaijia, that sucks! 

First of all thanks for showing me `npx` just googled it and that seems like a nice new tool by npm :).

For your problem I'm afraid I'm gonna have to redirect you to the [Stylelint repo](https://github.com/stylelint/stylelint/issues) though, as this very much sounds like a Stylelint bug.  I don't think there's anything we can do for that from a processor side.

I'll close this issue for now due to that, but if you get more information that insinuates we could do something about it feel free to comment here and maybe we'll reopen it, I do doubt it though, it definitely seems like a Stylelint bug.

**Comment by liunaijia** [comment]
Hi @emilgoldsmith , thanks for your prompt reply.

I reinstalled all the packages from fresh, the error was gone. I guess it would be caused by dependency issues.

Thanks,

**Comment by emilgoldsmith** [comment]
No problem :).

Good to hear! Yeah it might be that Stylelint's globbing dependency was causing issues I guess?

Good to hear your problem was fixed anyway :). Enjoy linting your Styled Components CSS!
