### ISSUE TITLE
Error with Node v4

### ISSUE THREAD

**Issue by plitex** [styled-components/stylelint-processor-styled-components#136]
Hi,

I'm facing a problem running the linter with node 4, node 6 and 8 is working fine.

```bash
> $ yarn lint:css                                                                                                                                            ⬡ 4.8.4 [±master ✓]
yarn run v1.2.1
$ stylelint './src/**/*.tsx'
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (/Users/plitex/dev/react/app/node_modules/stylelint/lib/dynamicRequire.js:5:10)
    at /Users/plitex/dev/react/app/node_modules/stylelint/lib/augmentConfig.js:342:23
    at Array.forEach (native)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Stylelint config:

```json
{
  "processors": ["stylelint-processor-styled-components"],
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-styled-components"
  ],
  "syntax": "scss"
}
```

**Comment by mxstbr** [comment]
PR welcome!
