### ISSUE TITLE
Requires typescript in non typescript project

### ISSUE THREAD

**Issue by corbanbrook** [styled-components/stylelint-processor-styled-components#32]
Running this plugin on a non typescript problem yielded the following error

```
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/node_modules/typescript-eslint-parser/parser.js:11:10)
```

Installing typescript fixes the problem but it should not be required on a non typescript project.

**Comment by ismay** [comment]
@corbanbrook You're right, apologies. It's because it's listed as a devDependency but should be in the regular deps. I'll fix it rightaway.
